spring.application.name=mls-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/mls_engine
spring.datasource.username=mls_admin
spring.datasource.password=change_me_locally
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=REPLACE_WITH_ENV_VARIABLE_DO_NOT_COMMIT
security.jwt.expiration-ms=3600000
server.port=8081
logging.level.org.springframework.security=DEBUG